[swarm_proxy]
redis_url = "redis://localhost/"
local_cache_size = 10000
max_connections = 1000
peer_timeout = 300 # seconds
proxy_addr = "127.0.0.1:8000"
jwt_secret = "your-secret-key-change-this"
worker_threads = 4
metrics_addr = "127.0.0.1:9100"
max_request_size = 10485760 # 10 MB
compression_level = 3

[bootstrap_nodes]
# Add your bootstrap nodes here
# Example: node1 = "127.0.0.1:9001"
# Example: node2 = "127.0.0.1:9002"